In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 2.6 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/12.3 MB 2.3 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.3 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.6/12.3 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.3 MB 2.0 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.3 MB 2.0 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.3 MB 1.9 MB/s eta 0:00:05
   ---------- ----------------------------- 3.1/12.3 MB 1.8 MB/s eta 0:00:06
   ----------- ---------------------------- 3.4/12.3 MB 1.8 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.3 MB 1.8 MB/s eta 0:00:05
   ------------- -------------------------- 4.2/12.3 MB 1.8 MB/s eta 0:00:05
   ----------

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
np.zeros((2,3))

[[1 2 3]
 [4 5 6]]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
#range
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
#zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#random
np.random.rand(3)

array([0.08023092, 0.69473194, 0.49355485])

In [16]:
import numpy as np
a=np.array([10,20,30,40])
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)


(4,)
1
4
int64
